name = "hyde-hyde-latex"
license = "MIT"
licenselink = "https://github.com/ray-g/hyde-hyde-latex/blob/master/LICENSE.md"
description = "A forked/derived version of Hyde"
tags = ["blog", "theme", "hyde", "highlight.js", "font-awesome", "google analytics", "disqus", "personal", "syntax highlighting", "responsive", "graphcomment"]
features = ["blog", "theme", "highlight.js", "font-awesome", "MathJax for latex"]
min_version = "0.33"

[author]
    name = "RayG"
    homepage = "https://ray-g.github.io"

# If Porting existing theme
[original]
    author =  "htr3n"
    homepage = "https://htr3n.github.io"
    repo = "https://github.com/htr3n/hyde-hyde"


